### ISSUE TITLE
Events do not show on Safari

### ISSUE THREAD

**Issue by xyanide** [ahmontero/bootstrap-calendar#3]
Somehow events do not show on Safari.
They work in all other browsers i checked but not in Safari (see screenshot: http://i48.tinypic.com/2e20607.png).

the javascript debugger doesn`t show any weird errors.

**Comment by ahmontero** [comment]
Hello, I have tried the calendar on Safari, and the events are showed. I have Safari version 5.1.7.

**Comment by xyanide** [comment]
On my Safari and my collegues safari it won`t work.

I`ve tried a local copy but no sigar.
I`m using a fresh installation of Safari 5.1.7. The debugger doesn`t show any errors.

If you need more info please do tell!

http://i48.tinypic.com/r8h4y9.png

**Comment by xyanide** [comment]
I did some more digging, and it seems like Safari doesn`t like the date format that is presented (http://www.bondigeek.com/blog/2011/01/18/handling-ddmmyyyy-date-strings-across-all-browsers/).

Safari returns a NaN for the following functions:
event_date.getMonth()
event_date.getDate()

Safari expects the date to be in the mm/dd/yyyy format, but is presented with a dd/mm/yyyy format.

http://www.bondigeek.com/blog/wp-content/uploads/2011/01/image_thumb3.png

**Comment by xyanide** [comment]
Alright, final solution :).

You must change the dateformat in the event array supplied on the demo page.

If you change it from:
{"date":"2012-12-12","title":"10"}
to:
{"date":"06/20/2012","title":"10"}

It will work.
I`ll put in a pull request for the fix

**Comment by rujenner** [comment]
I am using a download of the calendar (Feb 2013 version) and I've run into the problem not showing events in Safari. Is this issue resolved or do I need to modify date formats myself?

**Comment by xyanide** [comment]
The problem was fixed in the example back then.
I haven`t used this library since then.

You could check if the event dates look like the above solution example?
If that doens`t work i suggest you open a new ticket with your problem description.
