### ISSUE TITLE
The example calendar doesn`t show on Internet Explorer 9

### ISSUE THREAD

**Issue by xyanide** [ahmontero/bootstrap-calendar#4]
The page stays blank with Internet Explorer: http://ahmontero.github.com/bootstrap-calendar/.
Only the github image is shown.

The problem is with the given mime type according to Internet Explorer.
When I run the calendar local it works just fine.

**Comment by ahmontero** [comment]
This error may be related with the html uploaded to github. Thanks for reporting.

**Comment by ahmontero** [comment]
Fixed!

**Comment by xyanide** [comment]
Confirmed!
